### ISSUE TITLE
IHandle naming

### ISSUE THREAD

**Issue by dotnetchris** [danielwertheim/routemeister#2]
I hate to open an issue regarding naming but i really think you should try to come up with a better core interface than `IHandle<T>` i've probably created that same interface atleast 3 times already myself. For how integral that interface appears to be, allowing it to be easily collide with another library's and a user gets unexpected behavior because they picked the wrong namespace is not very helpful.

Maybe even something as silly as `IMeister<T>` you could always do it as an alias and just have `IMeister<T> : IHandle<T>` and then all your scanning stuff should just work as is and leave it up to the end user to use whichever flavor they like most.

**Comment by danielwertheim** [comment]
But there is no interface. That is up to the consumer to define.

**Comment by dotnetchris** [comment]
> you need to define

scrolled past that, you might want to just bold that on your blog post, and maybe mention it again somewhere lower that it's an interface the developer owns not routemeister.

I tend to read the first sentence or two of a blog post and immediately scroll to the code samples, then read code samples, then read text to fill in information

**Comment by danielwertheim** [comment]
Thanks. Will try and clarify. Will respond to blog comment when home.
