### ISSUE TITLE
Natively support Request/Response

### ISSUE THREAD

**Issue by pwhe23** [danielwertheim/routemeister#4]
Do you think it would make sense to add Request/Response support to routemeister? It might make it easier for others like me who would like to move away from MediatR. I primarily like the idea of routemeister where I can define my own IRequest<> and IRequestHandler<> interfaces so my Domain project won't know it even exists since everything is just registered in the IoC container. I would be willing to work on a pull request if that would help. I could also start a separate package with the Request/Response functionality that MediatR users could just drop in if that would make more sense.

**Comment by danielwertheim** [comment]
It's done, but not in that way. Perhaps it should exist in the Router instead? I added the concept of a Dispatcher which gives Send, Publish and Request-Response, which uses a Router underneath. The idea is that the router only should route while the dispatcher offers different messaging patterns and constraints like e.g. fail if Send gives to many route matches: https://github.com/danielwertheim/routemeister/blob/net-standard/src/projects/Routemeister/Dispatchers/AsyncDispatcher.cs#L30

You can still define your own interface, e.g. https://github.com/danielwertheim/routemeister/blob/net-standard/src/samples/Timings/Program.cs#L95

but I've also included pre-defined ones:

- https://github.com/danielwertheim/routemeister/blob/net-standard/src/projects/Routemeister/IAsyncRequestHandler.cs
- https://github.com/danielwertheim/routemeister/blob/net-standard/src/projects/Routemeister/IAsyncMessageHandler.cs

A simple test:
https://github.com/danielwertheim/routemeister/blob/net-standard/src/tests/Routemeister.UnitTests/Dispatchers/AsyncDispatcherTests.cs#L54

This is done. Just need to configure my new build server. With this release it will also switch to target .NET Standard: https://github.com/danielwertheim/routemeister/blob/net-standard/ReleaseNotes.md

Does this make sense?

**Comment by pwhe23** [comment]
Daniel, that looks *fantastic*. I'm giving a talk at one of our local user groups and I'm going to try to use this, I'll let you  know how it goes! It doesn't look like the release is out on Nuget yet, so I'll try to build locally.

**Comment by danielwertheim** [comment]
I'll finalize this and get it out in the evening.

**Comment by danielwertheim** [comment]
@pwhe23 There's now a pre-release out. I have nothing planned so it will be released as stable real soon (potentially today). Thought you could try it first: https://www.nuget.org/packages/Routemeister/2.0.0-pre8

Hope the talk goes well.

**Comment by pwhe23** [comment]
I'm checking 2.0.0-pre8 out now. It looks like there isn't any non-async support which might pose a bit of a challenge since I haven't gone down that path yet. Let's see how it goes :)

```
void Main()
{
    var assemblies = new[] { GetType().GetTypeInfo().Assembly };
    var container = new Container();
    
    var factory = new MessageRouteFactory();
    var routes = new MessageRoutes
    {
        factory.Create(assemblies, typeof (IAsyncRequestHandler<,>)),
    };
    var disp = new AsyncDispatcher((t, e) => container.GetInstance(t), routes);

    var ping = new Ping { Name = "Yo" };
    var pong = disp.RequestAsync(ping).Result;
    pong.Dump();
}

public class Ping : IRequest<Ping.Pong>
{
    public string Name { get; set; }
    
    public class Pong
    {
        public string Message { get; set; }
    };

    internal class Handler : IAsyncRequestHandler<Ping, Pong>
    {
        private readonly Service _service;

        public Handler(Service service)
        {
            _service = service;
        }
        
        public Task<Pong> HandleAsync(Ping cmd)
        {
            return Task.FromResult(new Pong
            {
                Message = _service.GetMessage(cmd.Name),
            });
        }
    };
};

public class Service
{
    public string GetMessage(string name)
    {
        return $"Howdy, {name}!";
    }
};
```
