### ISSUE TITLE
Support non-async

### ISSUE THREAD

**Issue by pwhe23** [danielwertheim/routemeister#6]
Do you think it would be reasonable to add support for non-async operations to routemeister? I have a huge code base that has literally hundreds of commands/queries that are all synchronous and do not return Tasks. I am looking into moving some of them to async, but probably not all of them, at least for a while.

I would be willing to submit a pull request if non-async is something you would be interested in routemeister supporting. It looks like these items would probably be affected since they reference a Task return type:

- MessageHandlerAction class, Invoke method
- MessageHandlerInvoker delegate

**Comment by danielwertheim** [comment]
I have nothing against adding pure sync support in there.

I haven't had time to look into what exactly need to change. Is there a change that lower parts might be able to change to return `object` and then the async path could cast to `Task`? The sync path can that make use of `object` for `void`, otherwise it might need two sub paths there...

**Comment by pwhe23** [comment]
That's pretty much exactly what I had in mind. Change Task to Object and cast wherever Async is needed. I guess void's would just return nulls to keep it simple. We'd create a non-async dispatcher also.

**Comment by danielwertheim** [comment]
PR #7 merged and new release is out on NuGet: https://www.nuget.org/packages/Routemeister/2.1.0

**Comment by pwhe23** [comment]
BTW: That IlMessageHandlerInvokerFactory code you wrote is pretty brilliant. I had never played with IlGenerator before and figuring out how to handle void methods was tricky but fun! The runtime threw some pretty gnarly error messages lol 😄
